---
title: "DATA 605 - Assignment 14"
author: "Amber Ferger"
date: "5/6/2020"
output: html_document
---

**Work out the Taylor Series Expansion for the following functions. For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion.**

For each of the following, we will assume that each function is analytic (can be represented by a power series) and use the fact that a Taylor Series Expansion takes the form of: 
$$f(x) = \sum_{n=0}^{\infty} \frac{f^n(a)}{n!}(x-a)^n = f(a) + f'(a)(x-a) + \frac{f''(a)}{2!}(x-a)^2 + \frac{f'''(a)}{3!}(x-a)^3 + \frac{f''''(a)}{4!}(x-a)^4 +...$$


$f(x) = \frac{1}{1-x}$  
  
First, we will find the derivatives of the function centered at 0 $(a=0)$:
$$f(x) = \frac{1}{1-x}, f(0) = \frac{1}{1} = 1$$
$$f'(x) = \frac{1}{(1-x)^2}, f'(0) = \frac{1}{1^2} = 1$$
$$f''(x) = \frac{2}{(1-x)^3}, f''(0) = \frac{2}{1^3} = 2$$
$$f'''(x) = \frac{6}{(1-x)^4}, f'''(0) =  \frac{6}{1^4} = 6$$
$$f''''(x) = \frac{24}{(1-x)^5}, f''''(0) = \frac{24}{1^5} = 24$$
  
The function takes on the form: 
$$f^n(0) = n!$$
  
For $-1<x<1$:
$$f(x) = f(a) + f'(a)(x-a) + \frac{f''(a)}{2!}(x-a)^2 + \frac{f'''(a)}{3!}(x-a)^3 + \frac{f''''(a)}{4!}(x-a)^4 +...$$
$$f(x) = 1 + x + \frac{2}{2!}x^2 + \frac{6}{3!}x^3 + \frac{24}{4!}x^4 +...$$
$$f(x) = 1 + x + x^2 + x^3 + x^4 +...$$
  
We can further simplify this equation as:
$$f(x) = \sum_{n=0}^{\infty} \frac{f^n(a)}{n!}(x-a)^n$$
$$\sum_{n=0}^{\infty} \frac{n!}{n!}x^n$$
$$\sum_{n=0}^{\infty} x^n$$
  



$f(x) = e^x$  
  
First, we will find the derivatives of the function centered at 0 $(a=0)$:
$$f(x) = e^x, f(0) = e^0 = 1$$
$$f'(x) = e^x, f'(0) = e^0 = 1$$
$$f''(x) = e^x, f''(0) = e^0 = 1$$
$$f'''(x) = e^x, f'''(0) = e^0 = 1$$
$$f''''(x) = e^x, f''''(0) = e^0 = 1$$
  
The function takes on the form:
$$f^n(0) = 1$$  
  
For $-\infty <x< \infty$: 
$$f(x) = f(a) + f'(a)(x-a) + \frac{f''(a)}{2!}(x-a)^2 + \frac{f'''(a)}{3!}(x-a)^3 +\frac{f''''(a)}{4!}(x-a)^4 +...$$
$$f(x) = 1 + x + \frac{1}{2!}x^2 + \frac{1}{3!}x^3 + \frac{1}{4!}x^4 +...$$
  
We can further simplify this equation as:
$$f(x) = \sum_{n=0}^{\infty} \frac{f^n(a)}{n!}(x-a)^n$$
$$\sum_{n=0}^{\infty} \frac{x^n}{n!}$$
  

$f(x) = ln(1+x)$

First, we will find the derivatives of the function centered at 0 $(a=0)$:
$$f(x) = ln(1+x), f(0) = ln(1) = 0$$
$$f'(x) = \frac{1}{1+x}, f'(0) = \frac{1}{1} = 1$$
$$f''(x) = - \frac{1}{(1+x)^2}, f''(0) = - \frac{1}{1^2} = -1$$
$$f'''(x) = \frac{2}{(1+x)^3}, f'''(0) = \frac{2}{1^3} = 2$$
$$f''''(x) = - \frac{6}{(1+x)^4}, f''''(0) = - \frac{6}{1^4} = -6$$
  
The function takes on the form:
$$f^n(0) = -1^{n+1}(n-1)!$$  
  
For $-1<x<1$:
$$f(x) = f(a) + f'(a)(x-a) + \frac{f''(a)}{2!}(x-a)^2 + \frac{f'''(a)}{3!}(x-a)^3 + \frac{f''''(a)}{4!}(x-a)^4 +...$$
$$f(x) = 0 + x - \frac{1}{2!}x^2 + \frac{2}{3!}x^3 - \frac{6}{4!}x^4+...$$
$$f(x) = x - \frac{1}{2}x^2 + \frac{1}{3}x^3 - \frac{1}{4}x^4+...$$  
  
We can further simplify this equation as:
$$f(x) = \sum_{n=0}^{\infty} \frac{f^n(a)}{n!}(x-a)^n$$
$$\sum_{n=0}^{\infty} \frac{-1^{n+1}(n-1)!}{n!} x^n$$
$$\sum_{n=0}^{\infty} \frac{-1^{n+1} x^n}{n}$$