---
title: "DATA 605 - Assignment 7"
author: "Amber Ferger"
date: "3/10/2020"
output: html_document
---

## Problem 1  
**Let $X_1$, $X_2$...$X_n$ be $n$ mutually independent random variables, each of which is uniformly distributed on the integers from 1 to $k$. Let $Y$ denote the minimum of the $X_i$s. Find the distribution of $Y$.**  

## Problem 2 
**Your organization owns a copier (future lawyers, etc.) or MRI (future doctors). This machine has a manufacturer's expected lifetime of 10 years. This means that we expect one failure every ten years. (Include the probability statements and R code for each part).**  

**a. What is the probability that the machine will fail after 8 years? Provide also the expected value and standard deviation. Model as a geometric. (Hint: the probability is equivalent to not failing during the first 8 years.)**  

**b. What is the probability that the machine will fail after 8 years? Provide also the expected value and standard deviation. Model as an exponential.**  

**c. What is the probability that the machine will fail after 8 years?. Provide also the
expected value and standard deviation. Model as a binomial. (Hint: 0 success in 8
years)**  


**d. What is the probability that the machine will fail after 8 years?. Provide also the
expected value and standard deviation. Model as a Poisson.** 